### ISSUE TITLE
High Package Size

### ISSUE THREAD

**Issue by MostafaSolimanMO** [AmremadDev/getworld#1]
**Description:**

I have noticed that the package has a significantly large size when analyzed using the flutter analyze-size command. The package currently occupies `27 MB`, which is larger than what is typically expected for a Flutter package. This size could potentially have an adverse impact on the performance and loading times of my application.

<img width="828" alt="Screenshot 2023-09-22 at 3 42 47 AM" src="https://github.com/AmremadDev/getworld/assets/43101916/b5457ee5-a1fb-4204-a8ed-df2c273db8f9">

**Comment by AmremadDev** [comment]
Hello Mostafa,

Thank you for using 'GetWorld' package  and for reporting your issue. I greatly appreciate it.

I primarily designed this package for retrieving data without the intention of incorporating it directly into your application. I understand that the package's size during runtime can be quite substantial, and unfortunately, I do not have a solution to load it partially in Dart.

Therefore, I would like to advise you to utilize this package for filtering data and exporting only the specific data you require into a smaller file. You can then use this smaller file in your Flutter project.

Once again, thank you for your support and feedback.

Best regards,
